### ISSUE TITLE
Drop Requires: line from fishsound.pc.in

### ISSUE THREAD

**Issue by michel-slm** [kfish/libfishsound#1]
This line is only needed if packages that build against libfishsound needs access to the Cflags of the required packages. In this case, the listed packages (vorbis, speex, flac) are precisely the packages that libfishsound provide a wrapper API for, so apps compiling against libfishsound really should not need their headers directly.

This was not a problem in 0.9.1, but in 1.0.0 the FLAC headers are exported, and this include a really regrettably misnamed assert.h, which shadows the system assert.h and causes compilation of sonic-visualiser to fail.

I've tried removing the Requires: line and can report that it results in a functioning sonic-visualiser build.

diff below:
    --- fishsound.pc.in.noreq   2009-03-28 04:40:03.000000000 +0100
    +++ fishsound.pc.in 2010-07-03 23:01:31.582347750 +0200
    @@ -5,7 +5,6 @@

```
 Name: fishsound
 Description: Encode and decode Vorbis, Speex, FLAC audio
-Requires: @fishsound_pkgdeps@
 Version: @VERSION@
 Libs: -L${libdir} -lfishsound
 Libs.private: @VORBIS_LIBS@ @SPEEX_LIBS@ @FLAC_LIBS@
```

**Comment by kfish** [comment]
Thanks, applied!
